export enum ScalerTypes {
  FastBilinear = 'fast_bilinear',
  Bilinear = 'bilinear',
  Bicubic = 'bicubic',
  Experimental = 'experimental',
  Neighbor = 'neighbor',
  Area = 'area',
  Bicublin = 'bicublin',
  Gauss = 'gauss',
  Sinc = 'sinc',
  Lanczos = 'lanczos',
  Spline = 'spline',
  PrintInfo = 'print_info',
  AccurateRnd = 'accurate_rnd',
  FullChromaInt = 'full_chroma_int',
  FullChromaInp = 'full_chroma_inp',
  Bitexact = 'bitexact',
}
